
@id = f84ba7b5-1a14-4651-b400-bbbd2bb97839
PUT  http://localhost:5079/user/{{id}}
Content-Type: application/json


{
"name": "Vegan Sunshine 2",
    "username": "Vegan everything! Join us for a healthy breakfast..",
    "password": "newpassword"
 
}